library(lubridate)
data<- read.table("/Users/deepikakulkarni/Documents/RCourse/EDA/household_power_consumption.txt", sep=";", header=TRUE,na.strings = c("?",""))
data$NewDate <- as.Date(data$Date, format="%d/%m/%Y")
dataPlot<- subset(data, NewDate >= "2007-2-1" & NewDate <= "2007-2-2")
dataPlot$x<-strptime(paste(dataPlot$NewDate, dataPlot$Time), "%Y-%m-%d %H:%M:%S")
dataPlot$Day<-weekdays(as.Date(dataPlot$x)
setwd("/Users/deepikakulkarni/Documents/RCourse/EDA")
#plot2.png#
png("Plot2.png", width = 480, height=480, type="quartz")
plot(dataPlot$x,dataPlot$Global_active_power,type="l", ylab="Global Active Power (kilowatts")
dev.off()
